version: '3.9'
services:
  database:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank-database
      - DB_EXTENSION="uuid-ossp"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 10
  backend:
    build: .
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=bank-database
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - database