openapi: '3.0.0'
info:
  title: Bank API
  description: Bank API
  version: 3.0.0
servers:
  - url: "http://localhost:8080"
    description: Mock
tags:
  - name: Healthcheck
  - name: Account
  - name: Transaction
paths:
  /healthcheck:
    get:
      tags:
        - Healthcheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
  /account:
    post:
      tags:
        - Account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
  /account/{id}:
    get:
      tags:
        - Account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
  /transaction:
    post:
      tags:
        - Transaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
components:
  schemas:
    Healthcheck:
      type: object
      properties:
        responses:
          type: string