openapi: '3.0.2'
info:
  title: Megaprof Backend API
  description: Essa é a documentação para os endpoints da API do backend Megaprof
  termsOfService: http://swagger.io/terms/
  contact:
    email: martinslucianofigueira@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Descubra mais sobre
  url: http://swagger.io
servers:
  - url: https://api.server.test/api
  - url: https://api.server.test/admin
tags:
  - name: API
    description: "API pública"
  - name: Admin
    description: "API administrativa"
paths:
  /healthcheck:
    get:
      tags:
        - API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
components:
  schemas:
    Healthcheck:
      type: object
      properties:
        responses:
          type: string